export const config = {
    "environment": process.env.REACT_APP_NODE_ENV,
    "companyName": "Techfully",
    "secretKey":process.env.REACT_APP_SECRET_KEY,
    "appBaseName":process.env.REACT_APP_BASENAME,
    "appGAID":process.env.REACT_APP_GAID,
    "captcha":"google",
    "apiRootPath": process.env.REACT_APP_API_ROOT_PATH ||"https://api.techfully.io",
    "authenticationURL":"/v1/authenticate",
    "registerURL":"/v3/registerUser",
    "resetURL":"/v1/sendOtp",
    "getChatData": "/v1/chatData",
    "getMetaDataURL":"/init/getMetaData",
    "websocketRootPath":process.env.REACT_APP_WEBSOCKET_ROOT_PATH || "ws://localhost:8000/",
    "eventConfigurationBaseURL":"http://localhost:4100/",
    "websocketURL":"ws://localhost:8000/api/ws/notification",
    "changePasswordURL":"/v1/updatePassword",
    "updateUserURL":"/v1/updateUser/",
    "loadDashboard":"/v1/exhibitor/summary",
    "loadAdminDashboard":"/v1/admin/summary",
    "validateOTP":"/v3/validateOtp",
    "resetPassword": "/v1/resetPassword",
    "feedbackUrl":"/v1/feedback",
    "loginEvent":"/v1/logEvent",
    "logoutEvent":/v1/logout,
    "getEvents":"getEvents",
    "getExhibitorsForEvent":"getExhibitorsForEvent"
};